import './globals.css'
import type { Metadata } from 'next'
import { Ubuntu_Mono } from 'next/font/google'
import { MainNav } from './components/Header/components/main-nav'
import { Header } from './components/Header'
import { headerConfig } from '@/config/header-config'
import { Socials } from './components/Socials'
import { socialsConfig } from '@/config/socials'
import { MobileNav } from './components/Header/components/mobile-nav/mobile-nav'

const ubuntu = Ubuntu_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`bg-[#28293D] text-white-primary ${ubuntu.className}`}>
        <Socials items={socialsConfig} />
        <Header>
          <MainNav items={headerConfig} />
          <MobileNav items={headerConfig} />
        </Header>
        {children}
      </body>
    </html>
  )
}
